// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juowzxgwkyjhsywosjdq.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1b3d6eGd3a3lqaHN5d29zamRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwODA5MzIsImV4cCI6MjA0OTY1NjkzMn0.d7DN49tEbZscjV6AOsXWYE_CNb1G7b3QmvUEMxwS2tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
